// Generated from the Apify scrape of instagram.com/jeffbells7 on 2026-09-19.
// Every figure here is the real reported number — do not hand-edit.

export type Reel = {
  id: string;
  url: string;
  views: number;
  viewsLabel: string;
  likes: number;
  likesLabel: string;
  comments: number;
  date: string;
  seconds: number;
  kind: "organic" | "product";
  local: boolean;
  caption: string;
};

export const REELS: Reel[] = [
  {
    id: "DVpBX77jmnW",
    url: "https://www.instagram.com/p/DVpBX77jmnW/",
    views: 3470005,
    viewsLabel: "3.47M",
    likes: 146166,
    likesLabel: "146.2K",
    comments: 168,
    date: "2026-03-08",
    seconds: 15,
    kind: "organic",
    local: false,
    caption: "",
  },
  {
    id: "DUMiUOkDlqt",
    url: "https://www.instagram.com/p/DUMiUOkDlqt/",
    views: 1245936,
    viewsLabel: "1.25M",
    likes: 96115,
    likesLabel: "96.1K",
    comments: 196,
    date: "2026-02-01",
    seconds: 17,
    kind: "organic",
    local: true,
    caption: "",
  },
  {
    id: "DU8oW7tDrRz",
    url: "https://www.instagram.com/p/DU8oW7tDrRz/",
    views: 865492,
    viewsLabel: "865.5K",
    likes: 29488,
    likesLabel: "29.5K",
    comments: 686,
    date: "2026-02-19",
    seconds: 11,
    kind: "organic",
    local: false,
    caption: "no liquids\ud83d\ude02",
  },
  {
    id: "DWNY417DMyu",
    url: "https://www.instagram.com/p/DWNY417DMyu/",
    views: 541702,
    viewsLabel: "541.7K",
    likes: 42714,
    likesLabel: "42.7K",
    comments: 649,
    date: "2026-03-23",
    seconds: 10,
    kind: "organic",
    local: false,
    caption: "",
  },
  {
    id: "DX12-bSuxkM",
    url: "https://www.instagram.com/p/DX12-bSuxkM/",
    views: 416947,
    viewsLabel: "416.9K",
    likes: 20778,
    likesLabel: "20.8K",
    comments: 164,
    date: "2026-05-02",
    seconds: 19,
    kind: "product",
    local: true,
    caption: "QuickMovee is a student-to-student campus app that helps college students get things done faster. Students can post quick paid tasks, get help from nearby verified students, earn extra money between classes, and buy,sell or trade items through QuickStop all with in-app chat and secure payments.",
  },
  {
    id: "DYdGp3LvhhL",
    url: "https://www.instagram.com/p/DYdGp3LvhhL/",
    views: 15457,
    viewsLabel: "15.5K",
    likes: 1022,
    likesLabel: "1K",
    comments: 7,
    date: "2026-05-17",
    seconds: 10,
    kind: "organic",
    local: false,
    caption: "",
  },
  {
    id: "DdKdkMVvY_W",
    url: "https://www.instagram.com/p/DdKdkMVvY_W/",
    views: 14872,
    viewsLabel: "14.9K",
    likes: 821,
    likesLabel: "821",
    comments: 8,
    date: "2026-09-11",
    seconds: 15,
    kind: "organic",
    local: false,
    caption: "\ud83e\udd77\u2019s be everywhere but class",
  },
  {
    id: "DZI8l2pPjGI",
    url: "https://www.instagram.com/p/DZI8l2pPjGI/",
    views: 12254,
    viewsLabel: "12.3K",
    likes: 162,
    likesLabel: "162",
    comments: 10,
    date: "2026-06-03",
    seconds: 10,
    kind: "organic",
    local: false,
    caption: "",
  },
  {
    id: "DZlcbQtuQdL",
    url: "https://www.instagram.com/p/DZlcbQtuQdL/",
    views: 11573,
    viewsLabel: "11.6K",
    likes: 633,
    likesLabel: "633",
    comments: 0,
    date: "2026-06-14",
    seconds: 11,
    kind: "organic",
    local: false,
    caption: "",
  },
  {
    id: "DWZ9cdGDltD",
    url: "https://www.instagram.com/p/DWZ9cdGDltD/",
    views: 10743,
    viewsLabel: "10.7K",
    likes: 386,
    likesLabel: "386",
    comments: 3,
    date: "2026-03-27",
    seconds: 11,
    kind: "organic",
    local: false,
    caption: "",
  },
  {
    id: "DYdasy1sTAm",
    url: "https://www.instagram.com/p/DYdasy1sTAm/",
    views: 10320,
    viewsLabel: "10.3K",
    likes: 511,
    likesLabel: "511",
    comments: 0,
    date: "2026-05-18",
    seconds: 11,
    kind: "organic",
    local: false,
    caption: "",
  },
  {
    id: "DX4zgqhvLfm",
    url: "https://www.instagram.com/p/DX4zgqhvLfm/",
    views: 8094,
    viewsLabel: "8.1K",
    likes: 223,
    likesLabel: "223",
    comments: 19,
    date: "2026-05-03",
    seconds: 10,
    kind: "organic",
    local: false,
    caption: "relatable?\ud83d\ude2d",
  },
  {
    id: "DdATXquuPOz",
    url: "https://www.instagram.com/p/DdATXquuPOz/",
    views: 7780,
    viewsLabel: "7.8K",
    likes: 204,
    likesLabel: "204",
    comments: 3,
    date: "2026-09-07",
    seconds: 10,
    kind: "organic",
    local: false,
    caption: "we om the same level\ud83d\ude2d",
  },
];

export const byId = (id: string) => REELS.find((r) => r.id === id)!;

/** Account-wide totals across all 52 reels scraped, not just the 13 shown. */
export const ACCOUNT = {
  totalViews: 6_794_221,
  totalViewsLabel: "6.79M",
  totalLikes: 345_418,
  totalLikesLabel: "345K",
  reelCount: 52,
  followers: 644,
  over400k: 5,
  over1m: 2,
  localViews: 1_710_534,
  localViewsLabel: "1.71M",
  localReels: 12,
  windowLabel: "Jan – Sep 2026",
};
